# Generated by Django 6.0.7 on 2026-08-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Food allergies or dietary restrictions', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_weight',
            field=models.FloatField(blank=True, help_text='Current weight in kg', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Maintain Weight', 'Maintain Weight'), ('Muscle Gain', 'Muscle Gain')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_weight',
            field=models.FloatField(blank=True, help_text='Goal weight in kg', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
    ]
