# Generated by Django 6.0.7 on 2026-09-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_profile_allergies_profile_current_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fitness_goal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
