# Generated by Django 6.0.7 on 2026-09-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_profile_fitness_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='goal_weight',
        ),
    ]
